name: ParrotLetter
version: '${project.version}'
main: me.xjuppo.parrotletter.ParrotLetter
api-version: 1.18

commands:
  parrotletter:
    usage: /parrotletter <subcommand>
    permission: parrotletter.*
    description: Base command
